name: gesturenlu
channels:
- pytorch
- nvidia
- conda-forge
- robostack-staging
- defaults
dependencies:
- python=3.11 # Make sure the correct Leap Python version is installed (https://github.com/petrvancjr/LeapAPI)
- numpy=1.26.4 # 1.24.3 Giovanni
- quaternion
- scikit-learn
- seaborn
- ros-humble-desktop
- ros-humble-realsense2-camera
- ros-humble-realsense2-camera-msgs
- ros-humble-realsense2-description
- ros-humble-librealsense2
- ros-humble-rqt-reconfigure
- ros-humble-tf-transformations
- ros-humble-rosbridge-server
- transforms3d
- spatialmath-python
- compilers # ROS2 utils
- cmake
- pkg-config
- make
- colcon-common-extensions
- rosdep
- opencv
- pynput
- scipy
- roboticstoolbox-python
- pymc=5.21.1 # (version might be omitted)
- fastdtw
- pytorch=2.3.1 # make sure the cpu version is NOT installed AND make sure all torch/vision/audio are from pytorch channel
- pytorch-cuda=11.8
- cudatoolkit=11.8
- torchvision
- torchaudio=2.3.1=py311_cu118
- python-sounddevice
- transformers=4.51.0
- accelerate
- git-lfs
- qt=5.15.8
- qt-main=5.15.8
- qt-webengine=5.15.8
- pyaudio
- gdown
- nltk # for whisperx
- tinyxml2>=10.0.0
- setuptools<65 # Due to ros-humble-desktop binaries
- pip
- pytest<8 # bigger version gets an error in VSCode
- dash
- plotly
- pip:
  - phonemizer
  - munch
  - kokoro
  - py-espeak-ng
  - soundfile
  - playsound
  - panda-python
  #- faster-whisper==1.1.0 
  #- ctranslate2==3.24.0 
  - librosa
  - fuzzywuzzy
  - pygobject