name: gesturenlu
channels:
- conda-forge
- robostack-staging
- defaults
- pytorch
- nvidia
dependencies:
- python=3.11 # Make sure the correct Leap Python version is installed (https://github.com/petrvancjr/LeapAPI)
- numpy=1.26.4 # 1.24.3 Giovanni
- quaternion
- scikit-learn
- seaborn
- ros-humble-desktop
- ros-humble-realsense2-camera
- ros-humble-realsense2-camera-msgs
- ros-humble-realsense2-description
- ros-humble-librealsense2
- ros-humble-rqt-reconfigure
- ros-humble-tf-transformations
- ros-humble-rosbridge-server
- transforms3d
- spatialmath-python
- compilers # ROS2 utils
- cmake
- pkg-config
- make
- colcon-common-extensions
- rosdep
- opencv
- pynput
- scipy
- roboticstoolbox-python
- pymc
- fastdtw
- pytorch=2.1 # make sure the cpu version is NOT installed
- pytorch-cuda=11.8
- cudatoolkit=11.8
- torchvision
#- torchaudio
- python-sounddevice
- transformers
- accelerate
- git-lfs
- qt=5.15.8
- qt-main=5.15.8
- qt-webengine=5.15.8
- pyaudio
- pip:
  - phonemizer
  - munch
  - py-espeak-ng
  - soundfile
  - playsound
  - panda-python
#  - mediapipe # ?
